app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'HomeController@index');

Route::auth();
Route::get('/login/verify_token', 'Auth\AuthController@getVerifyToken');
Route::post('/login/verify_token', 'Auth\AuthController@postVerifyToken');

Route::resource('/documents', 'DocumentController');
Route::resource('/categories', 'CategoryController');
Route::resource('/users', 'UserController');
Route::get('/profile', 'UserController@profile');

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'tfa_secret',
    ];

    /**
     * Check if the user has 2factor authentication enabled
     *
     * Using this accessor prevents issues with a number as first character for a function
     * @return boolean
     */
    public function getOtpEnabledAttribute()
    {
        return (bool)$this['attributes']['tfa_enabled'];
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

use App\Http\Requests;
use Illuminate\Support\Facades\Auth;
use PragmaRX\Google2FA\Google2FA;

class UserController extends BaseController
{
    /**
     * Create a new controller instance.
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();

        return view('user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        if($user === null) {
            flash('Gebruiker niet gevonden!', 'danger');

            return redirect()->action('UserController@index');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        if($user === null) {
            flash('Gebruiker niet gevonden!', 'danger');

            return redirect()->action('UserController@index');
        }

        // only allow editing your own user
        if(Auth()->user()->id != (int)$id /*|| Auth()->user->rank === 'admin'*/)
        {
            flash('Geen toegang!', 'danger');
            return redirect()->action('UserController@index');
        }

        $google2fa = new Google2FA();
        if($user->tfa_secret == null) {
            $user->tfa_secret = $google2fa->generateSecretKey(32);
        }
        $user->save();
        $qrCode = $google2fa->getQRCodeInline(
            env('APP_NAME'),
            $user->email,
            $user->tfa_secret
        );

        return view('user.edit', compact('user', 'qrCode'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($id);
        if($user === null) {
            flash('Gebruiker niet gevonden', 'danger');
            return redirect()->action('UserController@index');
        }
         // only edit your own user!
        if(Auth()->user()->id != (int)$id /*|| Auth()->user->rank === 'admin'*/)
        {
            flash('Geen toegang!', 'danger');
            return redirect()->action('UserController@index');
        }

        // enable or disable 2 FA
        $user->tfa_enabled = (bool)$request->get('2fa_enabled');

        $user->save();

        flash('Gebruiker bijgewerkt', 'info');
        return redirect()->back()->withInput();

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * Alias to edit authenticated user
     * @return \Illuminate\Http\Response
     */
    public function profile()
    {
        return $this->edit(Auth::user()->id);
    }
}

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Gebruiker bewerken</div>
                    <div class="panel-body">
                        {!! Form::open(['action'=>['UserController@update', $user->id], 'method'=>'post']) !!}
                        {!! Form::hidden('_method', 'PUT') !!}
                        {!! Form::label('name', 'Naam') !!}
                        {!! Form::text('name', $user->name, ['class' => 'form-control', 'required'=>true]) !!}

                        {!! Form::label('email', 'E-mailadres') !!}
                        {!! Form::email('email', $user->email, ['class'=>'form-control']) !!}

                        <br>
                        <div class="row">
                            <div class="col-md-12">
                                <h4>2 staps authenticatie</h4>
                                {!! Form::label('2fa_enabled', 'Gebruik authenticatie in twee stappen') !!}
                                {!! Form::hidden('2fa_enabled', 0) !!}
                                {!! Form::checkbox('2fa_enabled', 1) !!}
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <p>Gebruik de barcode om uw telefoon te koppelen.</p>
                                <img src="{{ $qrCode }}" class="img-responsive img-thumbnail"
                                     alt="2 staps authenticatie barcode: {{ $user->tfa_secret }}">
                                <br>
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <p>Of vul handmatig de volgende code in: </p>
                                <p><b>{{ $user->tfa_secret }}</b></p>
                            </div>
                        </div>
                        <br>
                        <br>
                        <div class="pull-right">
                            {!! Form::submit('Opslaan', ['class'=>'btn btn-primary']) !!}
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Gebruikers</div>
                    <div class="panel-body">
                        <div class="pull-right">
                            <a href="{{ action('UserController@create') }}" class="btn btn-primary">Gebruiker toevoegen</a>
                        </div>
                        <table class="table table-striped table-condensed">
                            <thead>
                            <th>ID</th>
                            <th>Naam</th>
                            <th>2FA</th>
                            <th>Opties</th>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <td>{{ $user->id }}</td>
                                    <td>{{ $user->name }}</td>
                                    <td>
                                        @if($user->otp_enabled)
                                            Ja
                                        @else
                                            Nee
                                        @endif
                                    </td>
                                    <td>
                                        {{--<a href="{{ action('UserController@show', ['id'=>$user->id]) }}" class="btn btn-default btn-sm">Bekijken</a>--}}
                                        <a href="{{ action('UserController@edit', ['id'=>$user->id]) }}" class="btn btn-default btn-sm">Bewerken</a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection